/** Gerado por scripts/gen-loot-catalog-ts.py — não editar a mao */

export const LOOT_NAMES: Record<string, string> = {
  "ESP-01": "Sal de Veia",
  "ESP-02": "Casca de Grimwald",
  "ESP-03": "Po Draconico Fino",
  "ESP-04": "Gelo Aromático",
  "ESP-05": "Musgo Seco de Cinza",
  "ESP-06": "Pimenta de Orc",
  "ESP-07": "Tempero Goblin (picante)",
  "ESP-08": "Salmour de Tunel",
  "ESP-09": "Ferrão Picante",
  "ESP-10": "Pluma Aromatica",
  "ESP-11": "Oleo de Engrenagem",
  "ESP-12": "Salmour Necro",
  "ESP-13": "Sangue em Po (desidratado)",
  "ESP-14": "Veneno Seco (comestivel trace)",
  "ESP-15": "Ácido em Po",
  "ESP-16": "Esporo Gourmet",
  "ESP-17": "Xilema Doce",
  "ESP-18": "Polen Caustico",
  "ESP-19": "Poeira de Arquivo",
  "ESP-20": "Cristal Triturado",
  "ESP-21": "Seda em Po",
  "ESP-22": "Resina Quente",
  "ESP-23": "Incenso de Valdrun",
  "ESP-24": "Eco de Lagrimas",
  "ESP-25": "Resina de Embalsamo",
  "ESP-26": "Essência Doppel",
  "ESP-27": "Incenso Celestial",
  "ESP-28": "Olho em Conserva",
  "ESP-29": "Coral Aromático",
  "ESP-30": "Orquidea Sorn (po)",
  "MIN-01": "Ferro Vulcanico (bruto)",
  "MIN-02": "Magnetita Flutuante",
  "MIN-03": "Po de Osso Fossil",
  "MIN-04": "Cobre de Masmorra",
  "MIN-05": "Cristal Vivo (fragmento)",
  "MIN-06": "Lasca de Aco Encantado",
  "MIN-07": "Quartzo Fantasma",
  "MIN-08": "Prata Viva",
  "MIN-09": "Prata Viva (veio)",
  "MIN-10": "Perola Turva",
  "MIN-11": "Madreperola Abissal",
  "MIN-12": "Obsidiana Vitrificada",
  "MIN-13": "Lodo Solidificado",
  "MIN-14": "Hematita Podre",
  "MIN-15": "Enxofre Amarelo",
  "MIN-16": "Gelo Eterno",
  "MIN-17": "Diamante Bruto (besouro)",
  "MIN-18": "Veneno Cristalizado",
  "MIN-19": "Madeira Viva (no)",
  "MIN-20": "Micelio Metalico",
  "MIN-21": "Seda Fossilizada",
  "MIN-22": "Nucleo de Mana (pequeno)",
  "MIN-23": "Pena Metalica",
  "MIN-24": "Ouro Liquido (frasco 50ml)",
  "MIN-25": "Quartzo Acustico",
  "MIN-26": "Cinza Petrificada",
  "MIN-27": "Resina de Construto",
  "MIN-28": "Elitro Condutor",
  "MIN-29": "Sangue Coagulado (mineral)",
  "MIN-30": "Fragmento de Altar",
  "TES-01": "Moedas Valdremor (saco 50)",
  "TES-02": "Moedas antigas (colecao)",
  "TES-03": "Gema de vidro (falso tesouro)",
  "TES-04": "Conteudo do Bau Falso",
  "TES-05": "Gema lapidada (pequena)",
  "TES-06": "Idolozinho de pedra",
  "TES-07": "Cristal ornamentado",
  "TES-08": "Reliquia de explorador",
  "TES-09": "Medalha de ordem extinta",
  "TES-10": "Joia de ouro (anel/col)",
  "TES-11": "Saco de gemas mistas",
  "TES-12": "Pergaminho selado (mapa/ritual)",
  "TES-13": "Carteira de seda cheia",
  "TES-14": "Obra de arte portable",
  "TES-15": "Coroa fragmentada",
  "TES-16": "Hoard draconico (mesa)",
  "TES-17": "Kit de joias de Matriarca",
  "TES-18": "Barra de platina",
  "TES-19": "Grimorio vazio (casca)",
  "TES-20": "Oferenda de Mira (flor preservada)",
};
