import type { TorAdversaryStats } from "./adversary-types";

/**
 * Bestiário completo do Um Anel (2ª ed.) — extraído de
 * livros/um-anel/08-mestre-e-adversarios.md ("Evil Men" até "Werewolves").
 * Habilidades Sinistras são texto informativo pro Mestre no v1 (gasto de
 * Ódio/Resolução pra ativá-las não é mecanizado ainda — ver plano da Fase 4,
 * "Deferido pra v1.1").
 */
export const TOR_ADVERSARIES: TorAdversaryStats[] = [
  // ——— Homens Maus ———
  {
    id: "invasor-do-sul",
    name: "Invasor do Sul",
    traits: "Astuto, Endurecido",
    tier: "mob",
    attributeLevel: 4,
    endurance: 16,
    might: 1,
    hate: 4,
    hateKind: "resolve",
    parry: 1,
    armour: 2,
    description: "Depois de um inverno rigoroso, Homens do Sul podem reunir bandos de guerra em busca de alguma propriedade isolada pra saquear.",
    actions: [
      { id: "machado", label: "Machado", rating: 3, damage: 5, injury: 18 },
      { id: "lanca-curta", label: "Lança Curta", rating: 2, damage: 3, injury: 14, specialDamage: ["Perfurar"] },
    ],
    fellAbilities: [
      { name: "Povo Feroz", text: "Gaste 1 Resolução pra ganhar (1d) e tornar a rolagem de ataque Favorecida." },
    ],
  },
  {
    id: "campeao-do-sul",
    name: "Campeão do Sul",
    traits: "Cruel, Resistente",
    tier: "elite",
    attributeLevel: 5,
    endurance: 20,
    might: 1,
    hate: 5,
    hateKind: "resolve",
    parry: 2,
    armour: 3,
    description: "Pode ser um cacique de Dunland, um senhor bandido capaz de unir guerreiros turbulentos numa pequena tropa, ou só um bandoleiro particularmente cruel.",
    actions: [
      { id: "lanca", label: "Lança", rating: 3, damage: 4, injury: 14, specialDamage: ["Perfurar"] },
      { id: "machado-longo", label: "Machado de Cabo Longo", rating: 3, damage: 6, injury: 18, specialDamage: ["Quebrar Escudo"] },
    ],
    fellAbilities: [
      { name: "Povo Feroz", text: "Gaste 1 Resolução pra ganhar (1d) num ataque e tornar a rolagem Favorecida." },
    ],
  },
  {
    id: "batedor-de-bolsos",
    name: "Batedor de Bolsos",
    traits: "Ágil, Precavido",
    tier: "mob",
    attributeLevel: 2,
    endurance: 8,
    might: 1,
    hate: 2,
    hateKind: "resolve",
    parry: 0,
    armour: 1,
    description: "Um bandido covarde, pronto pra roubar uma vítima indefesa, mas capaz de emboscar um companheiro solitário com ajuda de outros.",
    actions: [
      { id: "porrete", label: "Porrete", rating: 2, damage: 3, injury: 12 },
      { id: "arco", label: "Arco", rating: 2, damage: 3, injury: 14, specialDamage: ["Perfurar"] },
    ],
    fellAbilities: [
      { name: "Covarde", text: "Quando afetado pela Tarefa de Combate Intimidar Inimigo, a criatura também perde 1 Resolução." },
    ],
  },
  {
    id: "chefe-arruaceiro",
    name: "Chefe Arruaceiro",
    traits: "Implacável, Reservado",
    tier: "mob",
    attributeLevel: 3,
    endurance: 12,
    might: 1,
    hate: 3,
    hateKind: "resolve",
    parry: 1,
    armour: 2,
    description: "Mais resistente ou simplesmente mais feroz, um chefe é um arruaceiro que chegou ao topo com a ajuda de uma mente ou lâmina mais afiada.",
    actions: [
      { id: "espada-curta", label: "Espada Curta", rating: 3, damage: 3, injury: 16 },
      { id: "arco", label: "Arco", rating: 2, damage: 3, injury: 14, specialDamage: ["Perfurar"] },
    ],
    fellAbilities: [
      { name: "Grito de Triunfo", text: "Gaste 1 Resolução pra restaurar 1 Resolução a todos os outros Arruaceiros na luta." },
    ],
  },
  {
    id: "assaltante-de-estrada",
    name: "Assaltante de Estrada",
    traits: "Veloz, Vingativo",
    tier: "mob",
    attributeLevel: 4,
    endurance: 16,
    might: 1,
    hate: 4,
    hateKind: "resolve",
    parry: 0,
    armour: 2,
    description: "Mais perigoso que um bandido comum, um assaltante de estrada está acostumado à vida selvagem e sabe lidar com vítimas armadas.",
    actions: [
      { id: "lanca", label: "Lança", rating: 3, damage: 4, injury: 14, specialDamage: ["Perfurar"] },
      { id: "arco", label: "Arco", rating: 2, damage: 3, injury: 14, specialDamage: ["Perfurar"] },
    ],
    fellAbilities: [
      { name: "Velocidade de Serpente", text: "Quando alvo de um ataque, gaste 1 Resolução pra tornar a rolagem de ataque Desfavorecida." },
    ],
  },

  // ——— Orcs (todos: Ódio ao Sol) ———
  {
    id: "soldado-orc",
    name: "Soldado Orc",
    traits: "Rebelde, Vingativo",
    tier: "mob",
    attributeLevel: 3,
    endurance: 12,
    might: 1,
    hate: 3,
    hateKind: "hate",
    parry: 1,
    armour: 2,
    description: "Armados com as clássicas espadas tortas, os Soldados Orc são barulhentos e indisciplinados.",
    actions: [
      { id: "cimitarra", label: "Cimitarra", rating: 3, damage: 3, injury: 16 },
      { id: "lanca", label: "Lança", rating: 2, damage: 3, injury: 14, specialDamage: ["Perfurar"] },
    ],
    fellAbilities: [
      { name: "Covarde", text: "No início da rodada, foge do campo de batalha se estiver com 0 de Ódio e desengajado." },
      { name: "Odeia a Luz do Sol", text: "Perde 1 Ódio no início de cada rodada exposto à luz plena do sol." },
    ],
  },
  {
    id: "cacique-orc",
    name: "Cacique Orc",
    traits: "Cruel, Endurecido",
    tier: "elite",
    attributeLevel: 5,
    endurance: 20,
    might: 1,
    hate: 5,
    hateKind: "hate",
    parry: 3,
    armour: 3,
    description: "Só os Orcs mais cruéis vivem o bastante pra virar caciques e liderar seu bando à batalha.",
    actions: [
      { id: "cimitarra", label: "Cimitarra", rating: 3, damage: 3, injury: 16 },
      { id: "lanca", label: "Lança", rating: 3, damage: 3, injury: 14, specialDamage: ["Perfurar"] },
    ],
    fellAbilities: [
      { name: "Grande Salto", text: "Gaste 1 Ódio pra atacar qualquer herói, em qualquer postura, incluindo Retaguarda." },
      { name: "Velocidade de Serpente", text: "Quando alvo de um ataque, gaste 1 Ódio pra tornar a rolagem de ataque Desfavorecida." },
      { name: "Grito de Triunfo", text: "Gaste 1 Ódio pra restaurar 1 Ódio a todos os outros Orcs na luta." },
      { name: "Odeia a Luz do Sol", text: "Perde 1 Ódio no início de cada rodada exposto à luz plena do sol." },
    ],
  },
  {
    id: "chefe-grande-orc",
    name: "Chefe Grande Orc",
    traits: "Audaz, Astuto",
    tier: "boss",
    attributeLevel: 7,
    endurance: 48,
    might: 2,
    hate: 7,
    hateKind: "hate",
    parry: 3,
    armour: 4,
    description: "Uma estirpe poderosa de Orc, os Grandes Orcs — como Azog e seu filho Bolg — são frequentemente encontrados como líderes de seus parentes de sangue mais fraco.",
    actions: [
      { id: "cimitarra-pesada", label: "Cimitarra Pesada", rating: 3, damage: 5, injury: 18, specialDamage: ["Quebrar Escudo"] },
      { id: "lanca-de-ponta-larga", label: "Lança de Ponta Larga", rating: 3, damage: 5, injury: 16, specialDamage: ["Perfurar"] },
    ],
    fellAbilities: [
      { name: "Força Terrível", text: "Se a criatura causou um Golpe Perfurante com ataque corpo a corpo, gaste 1 Ódio pra tornar a rolagem de Proteção do alvo Desfavorecida." },
      { name: "Velocidade de Serpente", text: "Quando alvo de um ataque, gaste 1 Ódio pra tornar a rolagem de ataque Desfavorecida." },
      { name: "Grito de Triunfo", text: "Gaste 1 Ódio pra restaurar 1 Ódio a todos os outros Orcs na luta." },
      { name: "Odeia a Luz do Sol", text: "Perde 1 Ódio no início de cada rodada exposto à luz plena do sol." },
    ],
  },
  {
    id: "guarda-costas-grande-orc",
    name: "Guarda-costas Grande Orc",
    traits: "Feroz, Precavido",
    tier: "elite",
    attributeLevel: 6,
    endurance: 24,
    might: 2,
    hate: 6,
    hateKind: "hate",
    parry: 2,
    armour: 3,
    description: "Menos astutos do que quem os lidera, essas criaturas sinistras protegem seus capitães ao custo da própria vida.",
    actions: [
      { id: "machado-orc", label: "Machado Orc", rating: 3, damage: 3, injury: 18, specialDamage: ["Quebrar Escudo"] },
      { id: "lanca-de-ponta-larga", label: "Lança de Ponta Larga", rating: 3, damage: 5, injury: 16, specialDamage: ["Perfurar"] },
    ],
    fellAbilities: [
      { name: "Resistência Hedionda", text: "Quando um ataque causaria dano que reduziria a criatura a 0 de Resistência, causa um Golpe Perfurante em vez disso. Se a criatura ainda estiver viva, retorna à Resistência máxima." },
      { name: "Odeia a Luz do Sol", text: "Perde 1 Ódio no início de cada rodada exposto à luz plena do sol." },
    ],
  },
  {
    id: "arqueiro-goblin",
    name: "Arqueiro Goblin",
    traits: "Astuto, Olhos Aguçados",
    tier: "mob",
    attributeLevel: 2,
    endurance: 8,
    might: 1,
    hate: 2,
    hateKind: "hate",
    parry: 0,
    armour: 1,
    description: "Um Arqueiro Goblin é um Orc escolhido por sua visão aguçada. Sua capacidade de enxergar no escuro, aliada a mãos firmes, permite atirar flechas com precisão de dia ou de noite.",
    actions: [
      { id: "arco-de-chifre", label: "Arco de Chifre", rating: 3, damage: 3, injury: 14, specialDamage: ["Perfurar"] },
      { id: "faca-serrilhada", label: "Faca Serrilhada", rating: 2, damage: 2, injury: 14 },
    ],
    fellAbilities: [
      { name: "Covarde", text: "Quando afetado pela Tarefa de Combate Intimidar Inimigo, a criatura também perde 1 Ódio." },
      { name: "Veneno Orc", text: "Se um ataque resultar em Ferida, o alvo também é envenenado." },
    ],
  },
  {
    id: "guarda-orc",
    name: "Guarda Orc",
    traits: "Forte, Vigilante",
    tier: "mob",
    attributeLevel: 4,
    endurance: 16,
    might: 1,
    hate: 4,
    hateKind: "hate",
    parry: 2,
    armour: 3,
    description: "Os Orcs mais fortes e ousados são equipados com a armadura mais resistente que conseguem achar ou montar, e postos pra vigiar uma área com espada e escudo firme.",
    actions: [
      { id: "cimitarra", label: "Cimitarra", rating: 3, damage: 3, injury: 16 },
      { id: "lanca", label: "Lança", rating: 3, damage: 3, injury: 14, specialDamage: ["Perfurar"] },
    ],
    fellAbilities: [
      { name: "Odeia a Luz do Sol", text: "Perde 1 Ódio no início de cada rodada exposto à luz plena do sol." },
    ],
  },

  // ——— Trolls (todos: Resistência Hedionda + Obtuso) ———
  {
    id: "grande-troll-das-cavernas",
    name: "Grande Troll das Cavernas",
    traits: "Brutal, Perverso",
    tier: "boss",
    attributeLevel: 10,
    endurance: 80,
    might: 2,
    hate: 10,
    hateKind: "hate",
    parry: 0,
    armour: 3,
    description: "Enviado por Orcs pra esmagar as defesas e o moral dos inimigos que mais temem.",
    actions: [
      { id: "esmagar", label: "Esmagar", rating: 3, damage: 6, injury: 12, specialDamage: ["Agarrar"] },
      { id: "mordida", label: "Mordida", rating: 2, damage: 6, injury: 14, specialDamage: ["Perfurar"] },
    ],
    fellAbilities: [
      {
        name: "Resistência Hedionda",
        text: "Quando um ataque causaria dano que reduziria a criatura a 0 de Resistência, causa um Golpe Perfurante em vez disso. Se a criatura ainda estiver viva, retorna à Resistência máxima.",
      },
      {
        name: "Golpe de Pavor",
        text: "Gaste 1 Ódio pra fazer todos os heróis à vista ganharem 2 pontos de Sombra (Pavor). Quem falhar no Teste de Sombra fica atordoado e não pode gastar Esperança pelo resto da luta.",
      },
      { name: "Pele Grossa", text: "Gaste 1 ponto de Ódio pra ganhar (2d) numa rolagem de Proteção." },
      {
        name: "Obtuso",
        text: "Heróis em postura Avançado podem tentar uma Tarefa de Combate especial: rolagem de ENIGMA — sucesso reduz o Ódio do Troll em 1 (+1 por ícone de sucesso).",
      },
    ],
  },
  {
    id: "cave-troll-furtivo",
    name: "Cave-troll Furtivo",
    traits: "Furtivo, Precavido",
    tier: "elite",
    attributeLevel: 6,
    endurance: 50,
    might: 2,
    hate: 6,
    hateKind: "hate",
    parry: 0,
    armour: 3,
    description: "Essa estirpe de Cave-troll é menor que muitos de seus parentes, mas ainda maior que a maioria dos Orcs. Acostumado a viver nas profundezas da terra, um Cave-troll Furtivo costuma caçar sozinho e no escuro, contando com seu olfato aguçado.",
    actions: [
      { id: "clava", label: "Clava", rating: 3, damage: 6, injury: 16, specialDamage: ["Quebrar Escudo"] },
      { id: "mordida", label: "Mordida", rating: 2, damage: 6, injury: 14, specialDamage: ["Perfurar"] },
    ],
    fellAbilities: [
      { name: "Morador das Trevas", text: "Todas as rolagens de ataque são Favorecidas na escuridão." },
      { name: "Medo do Fogo", text: "Perde 1 Ódio no início de cada rodada engajado em combate corpo a corpo com um adversário empunhando tocha ou item em chamas." },
      { name: "Pele Grossa", text: "Gaste 1 ponto de Ódio pra ganhar (2d) numa rolagem de Proteção." },
    ],
  },
  {
    id: "ladrao-troll-de-pedra",
    name: "Ladrão Troll de Pedra",
    traits: "Faminto, Irritadiço",
    tier: "elite",
    attributeLevel: 8,
    endurance: 60,
    might: 2,
    hate: 8,
    hateKind: "hate",
    parry: 0,
    armour: 3,
    description: "A aparência de um Ladrão Troll de Pedra, embora sempre assustadora, é amenizada por sua tendência a vestir roupas simples, cozinhar comida e usar ferramentas como jarras e barris.",
    actions: [
      { id: "clava", label: "Clava", rating: 3, damage: 6, injury: 16, specialDamage: ["Quebrar Escudo"] },
      { id: "esmagar", label: "Esmagar", rating: 2, damage: 6, injury: 12, specialDamage: ["Agarrar"] },
    ],
    fellAbilities: [
      { name: "Ódio (Anões)", text: "Ao lutar contra Anões, todas as rolagens da criatura são Favorecidas." },
      { name: "Força Terrível", text: "Se a criatura causou um Golpe Perfurante, gaste 1 Ódio pra tornar a rolagem de Proteção do alvo Desfavorecida." },
    ],
  },
  {
    id: "chefe-troll-de-pedra",
    name: "Chefe Troll de Pedra",
    traits: "Cruel, Desconfiado",
    tier: "boss",
    attributeLevel: 9,
    endurance: 70,
    might: 2,
    hate: 9,
    hateKind: "hate",
    parry: 0,
    armour: 3,
    description: "Pequenos grupos de Trolls de Pedra podem se unir ao redor de um membro mais forte de sua estirpe, pra atacar caravanas de mercadores ou fazendas isoladas.",
    actions: [
      { id: "clava", label: "Clava", rating: 3, damage: 6, injury: 16, specialDamage: ["Quebrar Escudo"] },
      { id: "esmagar", label: "Esmagar", rating: 2, damage: 6, injury: 12, specialDamage: ["Agarrar"] },
    ],
    fellAbilities: [
      { name: "Ódio (Anões)", text: "Ao lutar contra Anões, todas as rolagens da criatura são Favorecidas." },
      { name: "Força Terrível", text: "Se a criatura causou um Golpe Perfurante, gaste 1 Ódio pra tornar a rolagem de Proteção do alvo Desfavorecida." },
      { name: "Grito de Triunfo", text: "Gaste 1 Ódio pra restaurar 1 Ódio a todos os outros Trolls na luta." },
    ],
  },

  // ——— Mortos-Vivos (todos: Sem Morte + Sem Coração + Golpe de Pavor) ———
  {
    id: "barrow-wight",
    name: "Barrow-wight",
    traits: "Astuto, Vingativo",
    tier: "elite",
    attributeLevel: 6,
    endurance: 24,
    might: 1,
    hate: 6,
    hateKind: "hate",
    parry: 0,
    armour: 3,
    description: "Enviado às colinas de Tyrn Gorthad pelo Rei-Bruxo de Angmar pra atormentar seus inimigos nas guerras contra Arnor, um Barrow-wight aparece como uma figura alta e sombria, com olhos frios acesos por uma luz pálida.",
    actions: [
      { id: "espada-antiga", label: "Espada Antiga", rating: 3, damage: 5, injury: 16, specialDamage: ["Perfurar"] },
      { id: "toque-gelido", label: "Toque Gélido", rating: 2, damage: 6, injury: 12, specialDamage: ["Agarrar"] },
    ],
    fellAbilities: [
      { name: "Morador das Trevas", text: "Todas as rolagens de ataque são Favorecidas na escuridão." },
      { name: "Feitiços Terríveis", text: "Gaste 1 Ódio pra fazer um herói ganhar 3 pontos de Sombra (Feitiçaria). Quem falhar no Teste de Sombra ou estiver Arrasado cai inconsciente e só acorda com uma rolagem de MÚSICA, ou depois de uma hora." },
      { name: "Odeia a Luz do Sol", text: "Perde 1 Ódio no início de cada rodada exposto à luz plena do sol." },
      { name: "Sem Morte", text: "Gaste 1 Ódio pra cancelar uma Ferida. Quando um ataque causaria dano que reduziria a criatura a 0 de Resistência, gaste 1 Ódio pra retornar à Resistência máxima. Ineficaz contra armas mágicas encantadas pra Perdição dos Mortos-Vivos." },
      { name: "Sem Coração", text: "A criatura não é afetada pela Tarefa de Combate Intimidar Inimigo, a menos que se obtenha um sucesso Mágico." },
    ],
  },
  {
    id: "espectro-funesto",
    name: "Espectro Funesto",
    traits: "Veloz, Precavido",
    tier: "mob",
    attributeLevel: 4,
    endurance: 16,
    might: 1,
    hate: 4,
    hateKind: "hate",
    parry: 1,
    armour: 2,
    description: "Espectros Funestos aparecem como andarilhos encurvados, vagando entre ruínas antigas, envoltos em capas que escondem seus traços espectrais. Sua carne é quase transparente, e seus olhos parecem brasas.",
    actions: [
      { id: "lamina-cravejada", label: "Lâmina Cravejada", rating: 3, damage: 4, injury: 16 },
      { id: "lanca-cruel", label: "Lança Cruel", rating: 2, damage: 4, injury: 14, specialDamage: ["Perfurar"] },
    ],
    fellAbilities: [
      { name: "Morador das Trevas", text: "Todas as rolagens de ataque são Favorecidas na escuridão." },
      { name: "Medo do Fogo", text: "Perde 1 Ódio no início de cada rodada engajado em combate corpo a corpo com um adversário empunhando tocha ou item em chamas." },
      { name: "Sem Morte", text: "Gaste 1 Ódio pra cancelar uma Ferida. Quando um ataque causaria dano que reduziria a criatura a 0 de Resistência, gaste 1 Ódio pra retornar à Resistência máxima." },
      { name: "Sem Coração", text: "A criatura não é afetada pela Tarefa de Combate Intimidar Inimigo, a menos que se obtenha um sucesso Mágico." },
    ],
  },
  {
    id: "habitantes-do-pantano",
    name: "Habitantes do Pântano",
    traits: "Ferozes, Furtivos",
    tier: "mob",
    attributeLevel: 3,
    endurance: 12,
    might: 1,
    hate: 3,
    hateKind: "hate",
    parry: 0,
    armour: 1,
    description: "Os Habitantes do Pântano são criaturas humanoides trôpegas, de carne pálida e úmida, como a de um cadáver deixado pra apodrecer na água. Uma luz sinistra em seus olhos pequenos sugere uma vitalidade e intenção perversas.",
    actions: [
      { id: "mordida", label: "Mordida", rating: 3, damage: 3, injury: 14, specialDamage: ["Perfurar"] },
      { id: "garras", label: "Garras", rating: 2, damage: 3, injury: 14, specialDamage: ["Agarrar"] },
    ],
    fellAbilities: [
      { name: "Medo do Fogo", text: "Perde 1 Ódio no início de cada rodada engajado em combate corpo a corpo com um adversário empunhando tocha ou item em chamas." },
      { name: "Odeia a Luz do Sol", text: "Perde 1 Ódio no início de cada rodada exposto à luz plena do sol." },
      { name: "Sem Morte", text: "Gaste 1 Ódio pra cancelar uma Ferida. Quando um ataque causaria dano que reduziria a criatura a 0 de Resistência, gaste 1 Ódio pra retornar à Resistência máxima." },
      { name: "Sem Coração", text: "A criatura não é afetada pela Tarefa de Combate Intimidar Inimigo, a menos que se obtenha um sucesso Mágico." },
    ],
  },

  // ——— Lobos Selvagens (todos: Grande Salto) ———
  {
    id: "warg",
    name: "Warg",
    traits: "Olhos Aguçados, Sombrio",
    tier: "mob",
    attributeLevel: 3,
    endurance: 12,
    might: 1,
    hate: 3,
    hateKind: "hate",
    parry: 0,
    armour: 1,
    description: "Lobos malignos de astúcia perversa e intenção maliciosa.",
    actions: [{ id: "presas", label: "Presas", rating: 3, damage: 3, injury: 14, specialDamage: ["Perfurar"] }],
    fellAbilities: [
      { name: "Grande Salto", text: "Gaste 1 Ódio pra atacar qualquer herói, em qualquer postura, incluindo Retaguarda." },
      {
        name: "Medo do Fogo",
        text: "Perde 1 Ódio no início de cada rodada engajado em combate corpo a corpo com um adversário empunhando tocha ou item em chamas.",
      },
      { name: "Velocidade de Serpente", text: "Quando alvo de um ataque, gaste 1 Ódio pra tornar a rolagem de ataque Desfavorecida." },
    ],
  },
  {
    id: "chefe-de-alcateia",
    name: "Chefe de Alcateia",
    traits: "Rápido, Cruel",
    tier: "elite",
    attributeLevel: 4,
    endurance: 16,
    might: 1,
    hate: 4,
    hateKind: "hate",
    parry: 0,
    armour: 1,
    description: "Maior em estatura, crueldade e astúcia que os Wargs comuns, um Chefe de Alcateia é convocado por seus parentes menores pra lidar com ameaças sérias. Nunca é encontrado sozinho, sempre cercado por uma alcateia de Wargs.",
    actions: [
      { id: "presas", label: "Presas", rating: 3, damage: 4, injury: 14, specialDamage: ["Perfurar"] },
      { id: "garras", label: "Garras", rating: 2, damage: 4, injury: 14, specialDamage: ["Agarrar"] },
    ],
    fellAbilities: [
      { name: "Grande Salto", text: "Gaste 1 Ódio pra atacar qualquer herói, em qualquer postura, incluindo Retaguarda." },
      { name: "Medo do Fogo", text: "Perde 1 Ódio no início de cada rodada engajado em combate corpo a corpo com um adversário empunhando tocha ou item em chamas." },
      { name: "Velocidade de Serpente", text: "Quando alvo de um ataque, gaste 1 Ódio pra tornar a rolagem de ataque Desfavorecida." },
      { name: "Uivo de Triunfo", text: "Gaste 1 Ódio pra restaurar 1 Ódio a todos os outros Wargs na luta." },
    ],
  },

  // ——— Lobisomens ———
  {
    id: "sabujo-de-sauron",
    name: "Sabujo de Sauron",
    traits: "Astuto, Feroz",
    tier: "boss",
    attributeLevel: 5,
    endurance: 20,
    might: 2,
    hate: 5,
    hateKind: "hate",
    parry: 1,
    armour: 2,
    description: "Escolhido por sua ferocidade e inteligência maliciosa, um Sabujo de Sauron é um servo do Senhor do Escuro, enviado numa missão precisa — reunir forças pra uma guerra vindoura, caçar um indivíduo específico, ou espionar uma área.",
    actions: [
      { id: "presas", label: "Presas", rating: 3, damage: 5, injury: 14, specialDamage: ["Perfurar"] },
      { id: "garras", label: "Garras", rating: 3, damage: 5, injury: 14, specialDamage: ["Agarrar"] },
    ],
    fellAbilities: [
      { name: "Ferida Mortal", text: "Alvos feridos fazem a rolagem de Dado de Proeza pra determinar a severidade da Ferida Desfavorecida." },
      {
        name: "Resistência Hedionda",
        text: "Quando um ataque causaria dano que reduziria a criatura a 0 de Resistência, causa um Golpe Perfurante em vez disso. Se a criatura ainda estiver viva, retorna à Resistência máxima.",
      },
      {
        name: "Golpe de Pavor",
        text: "Gaste 1 Ódio pra fazer todos os heróis à vista ganharem 3 pontos de Sombra (Pavor). Quem falhar no Teste de Sombra fica atordoado e não pode gastar Esperança pelo resto da luta.",
      },
    ],
  },

  // ——— Adversária única de Marco (livros/um-anel/13-apendice-patronos-e-ficha.md, "The Star of the Mist") ———
  {
    id: "elwen-a-espectra-funesta",
    name: "Elwen, a Espectra Funesta",
    traits: "Horrível, Pesarosa",
    tier: "boss",
    attributeLevel: 5,
    endurance: 24,
    might: 2,
    hate: 5,
    hateKind: "hate",
    parry: 2,
    armour: 2,
    description: "A nobre viúva do Senhor Hadirion, consumida pelo pesar após vê-lo torturado até a morte pelo Rei-Bruxo — ao longo dos anos, tornou-se a Espectra Funesta que assombra a Torre da Estrela na Bruma, no sopé sul das Montanhas Azuis.",
    actions: [
      { id: "lamina-corroida", label: "Lâmina Corroída", rating: 3, damage: 4, injury: 16, specialDamage: ["Perfurar"] },
      { id: "lanca", label: "Lança", rating: 2, damage: 4, injury: 14, specialDamage: ["Perfurar"] },
    ],
    fellAbilities: [
      { name: "Moradora das Trevas", text: "Rolagens de ataque são Favorecidas na escuridão." },
      { name: "Medo do Fogo", text: "Perde 1 Ódio no início de cada rodada engajada em combate corpo a corpo com um adversário empunhando tocha ou item em chamas." },
      {
        name: "Sem Morte",
        text: "Gaste 1 Ódio pra cancelar uma Ferida, ou dano que a levaria a 0 de Resistência. Imune à Tarefa de Combate Intimidar Inimigo, a menos que se obtenha um sucesso Mágico.",
      },
      {
        name: "Golpe de Pavor",
        text: "Gaste 1 Ódio pra fazer todos os heróis à vista ganharem 3 pontos de Sombra (Pavor). Quem falhar no Teste de Sombra se perde na névoa e não pode se reunir ao grupo até a rodada seguinte.",
      },
    ],
  },
];

export const TOR_ADVERSARY_BY_ID: Record<string, TorAdversaryStats> = Object.fromEntries(
  TOR_ADVERSARIES.map((a) => [a.id, a])
);
