# -*- coding: utf-8 -*-
"""Generaté livros/ASSIMILACAO-POR-ESPECIME.md"""
import re
from pathlib import Path

intro = """# ASSIMILACAO POR ESPECIME — Eldarin v4.0

Ao preparar um monstro especifico, o Prato Estruturado usa **esta tabela**, não a tabela da categoria ecologica. Cada espécime possui **8 habilidades** proprias. Nomes podem repetir entre monstros; a lista completa e sempre a dos 8 da ficha da criatura.

**Foco:** o Cozinheiro escolhe **1** habilidade da tabela do monstro preparado (garantida). **Rolagem do 1d4** (Cap. 5) define quantas escolhas extras o Cozinheiro faz, até **4 habilidades totais** no máximo.

**Duracao padrão:** 24 horas ou até o próximo descansó longo, salvo indicacao contraria. Efeitos estilo fantasia clássica; mutacoes não acumulam duplicatas do mesmo tipo.

---

"""

monsters = [
("001", "ZUMBI DE MASMORRA", [
("Levante Inevitavel", "Se reduzido a 0 HP por dano que não seja fogo ou radiante, volta com 1 HP após 1d4 turnos (1/combate)."),
("Memoria Muscular", "Vantagem em testes de uma profissao ou ferramenta ligada ao oficio do zumbi original (24h)."),
("Resistência Necrotica", "50% de resistência a dano necrótico (24h)."),
("Estômago de Putrefacao", "Imune a veneno e a Podridao de Masmorra nao-mágica (24h)."),
("Marcha Tenaz", "Ignora terreno dificil e armadilhas de fio; velocidade base -3m permanece (24h)."),
("Mordida Infecciosa", "Mordidas e ataques desarmados causam +1d4 necrótico (24h)."),
("Tolerancia a Dor", "Ignora penalidades leves de ferimento e exaustao de nivel 1 (24h)."),
("Aderencia Rasteira", "Move-se em velocidade maxima rastejando ou deitado (24h)."),
]),
("002", "ESQUELETO ARMADO", [
("Resistência Fantasmagorica", "Sofre metade do dano de ataques fisicos nao-magicos (24h)."),
("Marcha Silenciosa", "Vantagem em Furtividade; passos não produzem som em pedra ou metal (24h)."),
("Formacao de Falange", "+2 CA quando adjacente a 2 ou mais aliados (24h)."),
("Ossos Leves", "Sem dano de quedas até 9m; pesó efetivo reduzido pela metade (24h)."),
("Imunidade a Exaustao", "Imune a exaustao (24h)."),
("Resistência a Perfurante", "Resistência a dano perfurante (24h)."),
("Garras de Ossudo", "Ataques desarmados causam 1d6 cortante (24h)."),
("Medula Comprimida", "+2 em testes de Constituicao contra fadiga, sono forcado e exaustao (24h)."),
]),
("003", "NECRÓFAGO", [
("Mordida Paralisante", "Mordidas: CD 13 CON ou Paralisado por 1 turno (1/alvo/combate)."),
("Faro Cadavérico", "Detecta criaturas vivas até 30m, inclusive atras de paredes finas (24h)."),
("Instinto de Horda", "+2 em dano quando um aliado tambem ataca o mesmo alvo (24h)."),
("Estômago de Ferro", "Imune a penalidades por alimentos estragados ou podres (24h)."),
("Garras Necrofagicas", "Garras e mordidas causam +1d6 necrótico (24h)."),
("Adrenalina Covarde", "Velocidade dobra ao se afastar de inimigo claramente mais forte (24h)."),
("Visao de Submundo", "Visao perfeita no escuro absoluto (24h)."),
("Consumo Urgente", "Ao cair abaixo de 50% HP, ação bônus para um ataque extra (1/combate)."),
]),
("004", "ESPECTRO", [
("Passó Intangivel", "Atravessa portas trancadas ou paredes finas uma vez por combaté (24h)."),
("Toque Drenante", "Ataques desarmados causam necrótico e curam o personagem na mesma proporcao (24h)."),
("Levitacao Espectral", "Imune a armadilhas de pisó e terreno dificil (24h)."),
("Aura de Desespero", "Ao entrar em combate, inimigos a 5m: CD 12 SAB ou Desvantagem em ataques até sairem (1/combate)."),
("Olhos do Alem", "Ao tocar um cadaver, ve os ultimos 5 segundos de vida da criatura (24h)."),
("Resistência Fantasmagorica", "Metade do dano de ataques fisicos nao-magicos (24h)."),
("Corpo Translucido", "Quase invisivel em luz fraca; Vantagem em Furtividade em sombra (24h)."),
("Sexto Sentido Frio", "Nao pode ser surpreendido; detecta mortos-vivos num raio de 20m (24h)."),
]),
("005", "NECROARCA (ARQUILICHE)", [
("Resistência Lendaria", "Uma vez por combate, transforma falha em teste de resistência em sucessó (24h)."),
("Toque Paralisante", "Toque: CD 18 CON ou Paralisado por 1 minuto (1/alvo/combate)."),
("Consciencia Estendida", "Uma vez por dia, faz pergunta ao Mestre sobre segredo da masmorra atual (resposta criptica mas verdadeira) (24h)."),
("Imunidade Arcana", "Imune a medo, charm, exaustao e veneno (24h)."),
("Regeneração Necrotica", "Recupera 2d8 HP no inicio de cada turno enquanto a mutação estiver ativa (24h)."),
("Voo do Limiar", "Voo 9m por turno (24h)."),
("Olhos de Necroarca", "Enxerga ilusoes, invisibilidade e auras mágicas (24h)."),
("Disrupcao do Turno", "Reacao quando morto-vivo aliado a 30m cai a 0 HP: conjura truque ou magia de nv. 1 (1/combate)."),
]),
("006", "ASSOMBRACAO", [
("Perseguicao Implacavel", "Conhece posicao do alvo marcado em qualquer ponto do mesmo andar (marca 1 criatura ao comer; 24h)."),
("Toque Assombroso", "Ataques causam +1d8 psiquico; CD 14 SAB ou Amedrontado por 1 minuto (1/alvo/combate)."),
("Invisibilidade a Vontade", "Ação bônus para ficar invisivel por 1 turno (1/combate)."),
("Passó Intangivel", "Atravessa parede fina ou porta trancada uma vez por combaté (24h)."),
("Voz de Tumba", "Telepatia 30m; voz causa CD 12 SAB ou Amedrontado (1/combate)."),
("Levitacao Espectral", "Imune a armadilhas de pisó e terreno dificil (24h)."),
("Resistência Fantasmagorica", "Metade do dano de ataques fisicos nao-magicos (24h)."),
("Eco de Intencao", "Percebe intencao hostil de criaturas a 18m (24h)."),
]),
("007", "VAMPIRO", [
("Regeneração", "Recupera 10 HP no inicio de cada turno se não tomou radiante ou fogo no turno anterior (24h)."),
("Mordida Drenadora", "Mordidas +2d6 necrótico e curam metade do dano causado (24h)."),
("Nuvem de Morcegos", "Uma vez por combate, forma enxame ao se mover: imune a dano nao-magico por 1 turno."),
("Hipnose", "Contato visual: CD 17 SAB ou Encantado por 1 minuto (1/alvo/combate)."),
("Escalar Sombrio", "Velocidade de escalada igual ao movimento (24h)."),
("Visao Noturna Profunda", "Visao 36m no escuro; imune a cegueira por escuridao (24h)."),
("Resistência de Predador", "Resistência a necrótico e a dano fisico nao-magico (24h)."),
("Filhos da Noite", "Uma vez por dia, invoca distracao de morcegos: Vantagem em Furtividade por 1 hora (24h)."),
]),
("008", "CAVALEIRO ESPECTRAL", [
("Juramento Inabalavel", "Imune a charm, medo e efeitos que desviem atencao do alvo escolhido (24h)."),
("Golpe Espiritual", "Uma vez por turno, dano de arma passa por resistência fisica e vira necrótico (24h)."),
("Presenca Aterrorizante", "Inicio do combate: CD 15 SAB ou Amedrontado por 1 minuto num raio de 10m (1/combate)."),
("Armadura Espectral", "+3 CA; imune a veneno e exaustao (24h)."),
("Resistência Fantasmagorica", "Metade do dano de ataques fisicos nao-magicos (24h)."),
("Marcha Silenciosa", "Passos silenciosos em pedra e metal (24h)."),
("Sexto Sentido Frio", "Nao pode ser surpreendido; detecta mortos-vivos a 20m (24h)."),
("Aco Impregnado de Alma", "Detecta mortos-vivos e espiritos a 20m passivamente (24h)."),
]),
("009", "MUMIA", [
("Maldicao da Mumia", "Uma vez por turno em acerto: CD 15 CON ou alvo perde 10 HP máximo até descansó longo (24h)."),
("Resistência Fisica Antiga", "Resistência a contundente, perfurante e cortante nao-magico (24h)."),
("Imunidade Psiquica", "Imune a veneno, psiquico e exaustao (24h)."),
("Olhar Paralisante", "Acao: CD 14 SAB ou alvo Paralisado por 1 turno (1/combate)."),
("Linho Runico", "Buffs de refeicao e mutacoes de comida duram +4 horas (24h)."),
("Preservacao Temporal", "Maldicoes e venenos progridem metade da velocidade (24h)."),
("Faixas de Tempo", "+2 CA; pele resseca como faixa runica (24h)."),
("Aversao ao Fogo", "Vantagem em testes para evitar chamas e fogo ambiental (24h)."),
]),
("010", "DRAGONETE DE MAGMA", [
("Fornalha Interna", "Imune ao frio extremo; pode ferver liquidos segurando-os (24h)."),
("Sangue Fervente", "50% de resistência a dano de fogo e magma (24h)."),
("Toque Cauterizante", "Ataques corpo a corpo causam +1d6 de fogo (24h)."),
("Escalada Ignea", "Escala paredes de rocha e lava solidificada sem teste (24h)."),
("Escamas de Wyrm", "CA base aumenta em +2 (24h)."),
("Halito de Brasa", "Cospe cone de chamas 4m, 2d6 fogo, uma vez por combaté (24h)."),
("Ninhada Furiosa", "Quando aliado cai a 0 HP, +2 em ataques e +1d6 dano por 3 turnos (1/combate)."),
("Pulmoes de Fole", "Imune a gases, venenos inalados e esporos (24h)."),
]),
("011", "WYVERN", [
("Mergulho Rasante", "Se voar 9m em linha reta antes de atacar, mordida causa dano dobrado (24h)."),
("Ferrão Paralisante", "Uma vez por combate, acerto corpo a corpo: CD 15 CON ou Paralisado 1 minuto."),
("Visao de Predador", "Nao pode ser surpreendido em area aberta ou com teto alto (24h)."),
("Escamas de Wyrm", "CA base +2 (24h)."),
("Asas de Planagem", "Membranas sob bracos permitem planar controladamente (24h)."),
("Veneno de Cauda", "Ataques corpo a corpo +1d6 veneno (24h)."),
("Garras Retrateis", "Imune a empurroes involuntarios; pode prender inimigo pequeno (24h)."),
("Figado Alquimico", "Qualquer veneno no corpo e queimado para restaurar 1d6 Mana (1/dia)."),
]),
("012", "DRAGAO JOVEM DE GELO", [
("Sangue Anticongelante", "Imunidade total a dano de frio e penalidades de clima gelado (24h)."),
("Halito de Inverno", "Rajada de gelo cone 4m, 3d6 frio; apaga chamas (1/combate)."),
("Baforada Congelante", "Alvos atingidos por frio: CD 14 CON ou Paralisado 1 turno (1/combate)."),
("Escamas Draconicas", "CA base +3 (24h)."),
("Passos de Geada", "Agua congela sob as botas; pode correr sobre lagos e rios (24h)."),
("Presenca Aterrorizante", "CD 16 SAB ou Amedrontado 1 minuto (1/combate, raio 9m)."),
("Olhos de Dragão", "Enxerga auras mágicas e criaturas invisiveis (24h)."),
("Resistência Lendaria Menor", "Uma vez por combate, falha em teste vira sucessó (24h)."),
]),
("013", "DRAKE DE PEDRA", [
("Camuflagem de Pedra", "Em superficie de pedra, Vantagem em Furtividade; Percepção inimiga CD 18 para notar (24h)."),
("Pele de Granito", "Ataques nao-críticos abaixo de 8 de dano sao ignorados (24h)."),
("Mordida Esmagadora", "Mordida: CD 15 FOR ou Agarrado; enquanto agarrado, +1d6 contundente/turno (24h)."),
("Escavacao Rapida", "Escava terra ou cascalho a velocidade de caminhada (24h)."),
("Escamas de Wyrm", "CA base +2 (24h)."),
("Imunidade a Petrificação", "Imune a petrificação (24h)."),
("Resistência a Cortante", "Resistência a perfurante e cortante (24h)."),
("Cristais Minerais", "Detecta metais e gemas brutas a 10m atraves de rocha (24h)."),
]),
("014", "DRAGAO ANCIAO DE FOGO", [
("Resistência Lendaria", "Duas vezes por combate, falha em teste vira sucessó (24h)."),
("Baforada Devastadora", "Cone 9m, 8d6 fogo; falha em resistência: alvo em chamas +2d6 fogo/turno (1/combate)."),
("Pele de Adamante", "Ataques nao-magicos abaixo de 15 de dano sao ignorados (24h)."),
("Imunidade ao Fogo", "Imune a fogo; aura 1d6 fogo a inimigos adjacentes no inicio do turno deles (24h)."),
("Presenca Aterrorizante", "CD 21 SAB ou Amedrontado 1 minuto, raio 30m (1/combate)."),
("Memoria Draconica", "Uma vez por semana, pergunta ao Mestre sobre qualquer aspecto das masmorras (resposta verdadeira) (24h)."),
("Garras de Adamante", "Ataques desarmados cortam metal; +2d6 fogo em acerto (24h)."),
("Aura de Majestade", "Monstros de INT 5 ou menos não atacam primeiro sem provocação (24h)."),
]),
("015", "GOLEM DE PEDRA", [
("Absorção de Feiticos", "Feiticos de Abjuracao e Terra curam 10 HP em vez de causar dano (1/combate)."),
("Imutavel", "Imune a movimento, empurrao e queda involuntarios (24h)."),
("Comocao Sismica", "Acao: CD 15 DES ou Prostrado num raio de 3m (1/combate)."),
("Pele de Granito", "+3 CA; resistência a perfurante e cortante nao-magico (24h)."),
("Pulsó de Mana", "Imune a encantamento, ilusao e veneno (24h)."),
("Punhos de Pedra", "Ataques desarmados 2d6 contundente (24h)."),
("Marcha Inexoravel", "Ignora terreno dificil; velocidade não pode ser reduzida abaixo de metade (24h)."),
("Po Arcano", "+2 CA adicional por 6 horas após refeicao de construto (24h)."),
]),
("016", "ARMADURA ANIMADA", [
("Falsa Aparencia", "Imovel, indistinguivel de armadura comum (24h)."),
("Formacao de Guarda", "+2 CA quando adjacente a outra armadura aliada (24h)."),
("Marcha Silenciosa", "Sem som ao se mover em corredores de pedra (24h)."),
("Imunidade Psiquica", "Imune a veneno, psiquico, encantamento e exaustao (24h)."),
("Aco Encantado", "+2 CA base (24h)."),
("Golpe de Placa", "Ataques corpo a corpo +1d4 contundente (24h)."),
("Runa de Animação", "Uma vez por dia, comando verbal simples a constructo ou morto-vivo menor CD 13 SAB (24h)."),
("Blindagem Rigida", "Resistência a contundente nao-magico (24h)."),
]),
("017", "GOLEM DE FERRO VULCANICO", [
("Aura de Calor", "Inimigos adjacentes tomam 2d6 fogo no inicio do turno deles (24h)."),
("Sopro de Magma", "Cone 4,5m, 4d8 fogo, recarga 6 (1/combaté enquanto mutação ativa)."),
("Carcaça Imovel", "Imune a movimento involuntario (24h)."),
("Sangue Fervente", "50% resistência a fogo; imune a calor extremo (24h)."),
("Pele de Obsidiana", "Ignora dano extra de acertos críticos inimigos (24h)."),
("Punhos Vulcanicos", "Ataques corpo a corpo +2d6 fogo (24h)."),
("Ferro Vulcanico", "Armaduras e armas equipadas resistem a calor de forja (24h)."),
("Digestão Derretida", "Pode comer metais brutos para recuperar 2d6 HP (1/dia)."),
]),
("018", "AUTOMATO DE GENIO", [
("Analise de Ameaca", "Primeiros 2 turnos de combate: Vantagem em Percepção e Insight (24h)."),
("Mago de Combate", "Prepara 1 truque e 1 magia de nv. 1 adicional sem gastar espaco (24h)."),
("Nucleo Adaptativo", "Escolhe resistência a ultimo tipo de dano sofrido; dura até proxima refeicao (24h)."),
("Levitacao Mecanica", "Deslocamento de voo 9m; imune a armadilhas de pisó (24h)."),
("Fluido Arcano", "+2 em Inteligencia e testes de Arcana (24h)."),
("Memoria Eidetica", "Nao esquece mapas ou anotacoes feitas nas ultimas 24h (24h)."),
("Laminas Integradas", "Ataques desarmados 1d8+mod INT cortante (24h)."),
("Resistência Psiquica", "Resistência a psiquico; imune a exaustao (24h)."),
]),
("019", "MINOTAURO", [
("Investida", "Mover 3m em linha reta antes de atacar: +2d8 contundente no acerto (24h)."),
("Memoria de Labirinto", "Impossivel se perder em estruturas fechadas (24h)."),
("Brutalidade Natural", "Acerto acima de 20 de dano derruba alvo Prostrado (24h)."),
("Chifro Esmagador", "Ataques de investida ignoram metade da CA do alvo (1/combate)."),
("Couro Bestial", "+1 CA natural (24h)."),
("Faro de Territorio", "Detecta criaturas grandes a 30m (24h)."),
("Força do Touro", "+2 em Força e testes de Atletismo (24h)."),
("Instinto de Horda", "+2 dano quando aliado ataca o mesmo alvo (24h)."),
]),
("020", "BASILISCO", [
("Imunidade a Petrificação", "Imune a petrificação (24h)."),
("Olhar Petrificante", "Acao: alvo a 9m CD 12 CON ou Restringido; segunda falha consecutiva Petrificado (1/alvo/combate)."),
("Mordida Petrificante", "Mordidas +1d6 e CD 13 CON ou Petrificação imediata (1/alvo/combate)."),
("Camuflagem de Emboscada", "Vantagem em Furtividade quando imovel (24h)."),
("Escama Minerada", "+2 CA; resistência a perfurante (24h)."),
("Visao de Pedra", "Revela criaturas invisiveis e armadilhas ocultas num raio de 9m (24h)."),
("Patrulha Lenta", "Inimigos que iniciem combaté adjacentes: CD 12 CON ou velocidade 0 por 1 turno (1/combate)."),
("Carne Petrificante", "Resistência +4 em CON contra petrificação por 24h."),
]),
("021", "MANTICORA", [
("Salva de Espinhos", "Lança até 3 projeteis por turno, alcance 45m, +1d8 fogo cada (24h)."),
("Regeneração de Espinhos", "Recupera munição de espinhos após descansó curto (24h)."),
("Mordida de Leao", "Vantagem e +2d6 contra alvo Prostrado (24h)."),
("Voo Verdadeiro", "Voo 12m por turno (24h)."),
("Visao de Rapina", "Sem penalidade em ataques a longa distancia (24h)."),
("Territorio Marcado", "Vantagem em Percepção para detectar emboscadas (24h)."),
("Asas de Planagem", "Planar se cair (24h)."),
("Ossos Ocos", "Sem dano de quedas até 15m (24h)."),
]),
("022", "GRIFO", [
("Mergulho de Rapina", "Cair 9m antes de atacar: 4d8 contundente e Agarrado CD 16 FOR (24h)."),
("Visao de Aguia", "Visao perfeita no escuro 60m; imune a ilusoes visuais (24h)."),
("Par Eterno", "Se aliado cai a 0 HP a 60m, Furia: +4 dano e Vantagem em ataques por 10 min (1/combate)."),
("Voo Verdadeiro", "Voo 12m por turno (24h)."),
("Garra de Grifo", "+3 em testes de Trinchar quando usa garra como ferramenta (24h)."),
("Penas de Voo", "+9m de salto; Vantagem em Percepção e Iniciativa (24h)."),
("Nobreza Bestial", "Vantagem em Intimidacao contra feras (24h)."),
("Ossos Ocos", "Sem dano de quedas até 15m; saltos triplicam (24h)."),
]),
("023", "COCATRIZ", [
("Bico Petrificante", "Acertos: CD 11 CON ou Restringido; terceira falha Petrificado 24h (24h)."),
("Frenesi de Bicada", "Dois ataques de bico por turno se tiver Vantagem (24h)."),
("Imunidade a Petrificação", "Imune a petrificação (24h)."),
("Voo de Gallo", "Voo 12m; Vantagem em Furtividade ao pousar (24h)."),
("Saliva Catalitica", "Arma corpo a corpo +1d4 e CD 11 CON ou Restringido (1/alvo/combate)."),
("Ovo Nutritivo", "+4 em CON contra petrificação por 24h; +10 HP temporarios na refeicao."),
("Plumagem Furtiva", "Passos silenciados (24h)."),
("Furia Desproporcional", "+2 em ataques contra alvos maiores que você (24h)."),
]),
("024", "ARANHA TECERROCHAS", [
("Aderencia de Quitina", "Escala paredes e tetos lisos perfeitamente, sem teste (24h)."),
("Glandula Fibrilar", "Dispara teias das palmas (alcance 9m); imobiliza ou serve como corda (24h)."),
("Sentido de Teia", "Detecta qualquer criatura que toque uma teia sua ou aliada a 30m (24h)."),
("Veneno Paralisante Leve", "Mordidas CD 11 CON ou -3m movimento por 1 hora (24h)."),
("Olhos Compostos", "Visao periferica 360 graus; imune a flanqueamento (24h)."),
("Armadura Fina", "Quitina sob pele: +2 CA (24h)."),
("Patas Multiplas", "Velocidade base +5m (24h)."),
("Metabolismo Filtrador", "Imune a venenos e doenças nao-mágicas (24h)."),
]),
("025", "ESCORPIAO GIGANTE", [
("Garras Implacaveis", "Agarramento automatico em acerto; escape CD 14 FOR ou Acrobacia (24h)."),
("Ferrão Venenoso", "Contra alvo agarrado: CD 13 CON ou Envenenado 1 hora (24h)."),
("Armadura Natural", "Ignora primeiros 5 de dano cortante por ataque (24h)."),
("Sentido Sismico", "Visao as cegas 10m; detecta movimento no solo (24h)."),
("Armadura Fina", "+2 CA (24h)."),
("Quelíceras Acidicas", "Corpo a corpo +1d6 veneno (24h)."),
("Metabolismo Filtrador", "Imune a venenos e doenças nao-mágicas (24h)."),
("Patas Multiplas", "Velocidade +5m (24h)."),
]),
("026", "CENTOPEIA CAUSTICA", [
("Rastro Ácido", "Terreno onde passa causa 1d4 ácido por cruzar (1 minuto; 24h)."),
("Agarramento Corrosivo", "Envolver presa: CD 15 FOR ou Restringido; +2d6 ácido/turno (24h)."),
("Segmentos Autonomos", "Uma vez por combate, ignora efeito que reduziria a 0 HP e fica com 1 HP (24h)."),
("Quelíceras Acidicas", "Corpo a corpo +1d6 ácido (24h)."),
("Aderencia de Quitina", "Escala qualquer superficie sem teste (24h)."),
("Metabolismo Filtrador", "Imune a venenos e doenças nao-mágicas (24h)."),
("Pele Poro-Acida", "Resistência a ácido; atacante corpo a corpo toma 1d4 ácido (24h)."),
("Patas Multiplas", "Velocidade +5m (24h)."),
]),
("027", "BESOURO-DIAMANTE", [
("Exoesqueleto Reflexivo", "Ataques cortantes que falhem por 3 ou menos refletem 1d4 no atacante (24h)."),
("Armadura Fina", "+2 CA (24h)."),
("Resistência a Cortante", "Resistência a perfurante e cortante (24h)."),
("Mandibulas de Diamante", "Ataques desarmados 1d6 cortante; +2 em testes para quebrar objetos (24h)."),
("Pedra de Afiar Viva", "Arma empunhada ganha +1 dano por 24h após afiar com quitina (24h)."),
("Metabolismo Filtrador", "Imune a venenos e doenças nao-mágicas (24h)."),
("Sentido Sismico", "Detecta vibracao no chao 10m (24h)."),
("Patas Multiplas", "Velocidade +3m (24h)."),
]),
("028", "SAPO-ENGOLIDOR", [
("Lingua Veloz", "Ataque de alcance 6m; acerto Agarra CD 14 FOR (24h)."),
("Engolimento", "Alvo Agarrado pode ser puxado e engolido: 3d6 ácido/turno interno (1/combate)."),
("Salto Anfibio", "Salto horizontal 6m sem teste (24h)."),
("Guelras de Profundeza", "Respiração aquatica infinita (24h)."),
("Pele Escorregadia", "Impossivel ser agarrado ou imobilizado por correntes (24h)."),
("Bexiga Natatoria", "Flutua no ar ou armazena oxigenio para 1 aliado 10 min (24h)."),
("Visao de Mosca", "Vantagem em Percepção contra criaturas em movimento rapido (24h)."),
("Lingua Adesiva", "Estende lingua 3m para desarmar ou puxar objeto (24h)."),
]),
("029", "KRAKEN MENOR", [
("Tentaculos Multiplos", "Pode agarrar até 2 alvos; agarrado toma 2d6 esmagamento/turno (24h)."),
("Jato de Tinta Cega", "Nuvem raio 6m; CD 15 CON ou Cego 1 minuto (1/combate)."),
("Bioeletricidade", "Ataques +1d6 eletrico; metal em contato descarrega 1d6 (24h)."),
("Guelras de Profundeza", "Respiração aquatica infinita (24h)."),
("Radar de Linha Lateral", "Sente movimento e batimentos atras de paredes finas ou agua (24h)."),
("Resistência Abissal", "Imune a esmagamento e mudancas extremas de pressao (24h)."),
("Camuflagem de Polvo", "Invisivel ao colar em parede ou rocha umida (24h)."),
("Imersao Profunda", "Aliado agarrado pode ser submersó 60m sem teste de CON (1/dia)."),
]),
("030", "SERPENTE-DO-ABISMO", [
("Constricao", "Acerto de mordida: CD 14 FOR ou Agarrado; 2d6/turno (24h)."),
("Anfibia Perfeita", "Sem penalidade em terra ou agua (24h)."),
("Veneno Neurotoxico", "Mordida CD 13 CON ou Envenenado e -4 DES por 1 hora (24h)."),
("Pele Escorregadia", "Impossivel ser agarrado ou imobilizado (24h)."),
("Camuflagem Abissal", "Vantagem em Furtividade em agua ou escuridao total (24h)."),
("Guelras de Profundeza", "Respiração aquatica infinita (24h)."),
("Radar de Linha Lateral", "Detecta calor e movimento a 15m (24h)."),
("Mordida Profunda", "Mordidas +1d8 veneno (24h)."),
]),
("031", "TUBARAO-CEGO", [
("Sentido de Vibracao", "Detecta movimento na agua 60m; em terra 10m (24h)."),
("Impulsó Sanguinario", "Vantagem e +3m movimento contra alvos Sangrando (24h)."),
("Frenesi em Bando", "Com 2+ aliados adjacentes ao alvo: +2 em ataques (24h)."),
("Imunidade a Ilusao Visual", "Imune a ilusoes visuais e cegueira por luz (24h)."),
("Radar de Linha Lateral", "Sente batimentos atras de agua ou parede fina (24h)."),
("Mordida Predadora", "Mordidas +2d6 perfurante (24h)."),
("Escamas Bioluminescentes", "Emite luz fraça 3m; aliados ganham +1 em Percepção no escuro (24h)."),
("Resistência Abissal", "Imune a pressao extrema e esmagamento (24h)."),
]),
("032", "GOBLIN DE CAVERNA", [
("Estômago de Ferro", "Imune a penalidades por alimentos estragados (24h)."),
("Instinto de Horda", "+2 dano quando aliado ataca o mesmo alvo (24h)."),
("Faro para Ouro", "Detecta metais preciosos atras de paredes até 10m (24h)."),
("Adrenalina Covarde", "Velocidade dobra ao fugir de inimigo mais forte (24h)."),
("Garras de Escavador", "Escava terra ou cascalho a velocidade de caminhada (24h)."),
("Visao de Submundo", "Visao perfeita no escuro (24h)."),
("Ataque Furtivo", "+2d6 se tiver Vantagem no ataque (24h)."),
("Coordenacao de Horda", "+1 ataque por aliado goblinoide adjacente ao alvo, max +4 (24h)."),
]),
("033", "HOBGOBLIN GUERREIRO", [
("Vantagem Marcial", "+2d6 se aliado atacou o mesmo alvo no turno (24h)."),
("Formacao de Batalha", "Com 2+ hobgoblins aliados: imune a efeitos de medo (24h)."),
("Instinto de Horda", "+2 dano com aliado no mesmo alvo (24h)."),
("Disciplina de Placa", "+1 CA e +1 em testes de resistência (24h)."),
("Metabolismo Acelerado", "Descansó curto e longo em metade do tempo (24h)."),
("Visao de Submundo", "Visao perfeita no escuro (24h)."),
("Marcha Militar", "Velocidade +3m em formacao com aliados (24h)."),
("Estômago de Ferro", "Imune a penalidades por comida podre (24h)."),
]),
("034", "ORC DE MASMORRA", [
("Agressivo", "Ação bônus: mover até velocidade em direcao ao inimigo mais próximo (24h)."),
("Resistência de Orc", "Primeira vez por dia a 0 HP, cai a 1 HP (24h)."),
("Força Bruta", "+4 em Força e testes de Atletismo (24h)."),
("Instinto de Horda", "+2 dano com aliado no mesmo alvo (24h)."),
("Visao de Submundo", "Visao perfeita no escuro (24h)."),
("Furia Contida", "Uma vez por combate, +1d12 dano em um acerto (24h)."),
("Estômago de Ferro", "Imune a penalidades por comida podre (24h)."),
("Garras de Escavador", "Escava terra a velocidade de caminhada (24h)."),
]),
("035", "COGUMELO-REI", [
("Esporos Curativos", "Ação bônus cura aliado a 9m em 2d8 HP (1/combate)."),
("Imunidade Mental", "Imune a encantamento e ilusao nao-mágica (24h)."),
("Mente-de-Colmeia", "Telepatia com aliados a 30m; +2 em Iniciativa de grupo (24h)."),
("Metabolismo Filtrador", "Imune a venenos e doenças nao-mágicas (24h)."),
("Nuvem Alucinogenia", "Raio 6m CD 14 SAB ou Encantado 10 min (1/combate)."),
("Hifa Resistente", "+2 CA; resistência a perfurante (24h)."),
("Digestão Fungica", "Pode comer plantas e fungos toxicos sem penalidade (24h)."),
("Rede Micelial", "Sente movimento de criaturas a 20m atraves de fungos ou solo orgânico (24h)."),
]),
("036", "TREANT PODRE", [
("Gas de Decomposicao", "Inimigos a 3m: CD 13 CON ou Envenenado (24h)."),
("Raizes de Agarramento", "Acao: CD 16 FOR ou Restringido (1/combate)."),
("Casca de Ferro Podre", "Ataques cortantes causam no minimo 1d4 (24h)."),
("Resistência Necrotica", "Resistência a necrótico; imune a exaustao (24h)."),
("Madeira Necrotica", "Toque em morto-vivo cura 2d6 (1/combate) ou causa 2d6 radiante em morto-vivo hostil (24h)."),
("Passos Pesados", "Ataques corpo a corpo empurram alvo 3m em acerto (24h)."),
("Resistência Contundente", "Resistência a contundente e perfurante (24h)."),
("Seiva Podre", "Armas corpo a corpo +1d6 necrótico por 3 turnos (1/combate)."),
]),
("037", "PLANTA CARNIVORA GIGANTE", [
("Aroma Narcotico", "Criaturas a 5m CD 12 SAB ou movem-se em direcao ao cheiro (1/combate)."),
("Gavinhas Multiplas", "Pode agarrar 2 alvos; escape CD 14 FOR (24h)."),
("Estômago Digestivo", "Alvo Restringido dentro de gavinha toma 4d6 ácido/turno (24h)."),
("Glandula Fibrilar", "Dispara gavinha 9m; imobiliza (24h)."),
("Raiz Elastica", "Corda natural ou salto +3m (24h)."),
("Flor Narcotica", "Vantagem em testes de Persuasao com aroma adocicado (24h)."),
("Metabolismo Filtrador", "Imune a venenos vegetais nao-magicos (24h)."),
("Camuflagem Vegetal", "Vantagem em Furtividade entre flora (24h)."),
]),
("038", "SLIME ACIDO", [
("Divisao", "Quando atingido por cortante, divide-se: reduz dano recebido pela metade uma vez por combaté (24h)."),
("Corrosao de Armadura", "Contato 3 turnos: -1 CA cumulativo em armadura metalica (24h)."),
("Absorção", "Alvo em contato CD 12 FOR ou puxado 1,5m (24h)."),
("Corpo de Lodo", "Passa por frestas de 2,5cm; resistência a ácido (24h)."),
("Metabolismo Filtrador", "Imune a venenos nao-magicos (24h)."),
("Toque Ácido", "Corpo a corpo +2d6 ácido (24h)."),
("Amorfismo", "Imune a crítico por perfuracao (24h)."),
("Digestão Derretida", "Pode dissolver trancas mundanas em 1 minuto de contato (24h)."),
]),
("039", "SLIME DE CRISTAL", [
("Projecao de Cristais", "Cone 3m 2d4 cortante, recarga 5-6 (24h)."),
("Reflexo de Luz", "Feiticos de luz direcionados a você refletem aleatoriamente (24h)."),
("Juntas Articuladas", "Escapa de restricoes fisicas com Vantagem (24h)."),
("Resistência a Cortante", "Resistência a cortante e ácido (24h)."),
("Corpo de Lodo", "Passa por frestas de 2,5cm (24h)."),
("Camuflagem Cristalina", "Vantagem em Furtividade em ambiente cristalino (24h)."),
("Pele Mutavel", "Altera brilho e cor da pele como camuflagem (24h)."),
("Armadura Fina", "Cristais sob pele +2 CA (24h)."),
]),
("040", "ELEMENTAL DE FOGO", [
("Forma de Fogo", "Imune a ataques nao-magicos; atacantes corpo a corpo tomam 2d6 fogo (24h)."),
("Sangue Fervente", "Imune a fogo; 50% resistência a magma (24h)."),
("Halito de Brasa", "Cone 4m 3d6 fogo, 1/combaté (24h)."),
("Toque Cauterizante", "Corpo a corpo +1d6 fogo (24h)."),
("Iluminacao", "Emite luz 18m; não pode ser surpreendido por escuridao (24h)."),
("Suor Fumegante", "Ataques a distancia contra você tem Desvantagem (24h)."),
("Pegadas de Magma", "Rastro 1d6 fogo a quem seguir (24h)."),
("Absorção de Chama", "Primeiro ataque de fogo recebido cura 2d6 HP (1/combate)."),
]),
("041", "ELEMENTAL DE GELO", [
("Forma de Gelo", "Imune a ataques nao-magicos cortantes (24h)."),
("Sangue Anticongelante", "Imune a frio (24h)."),
("Halito de Inverno", "Cone 4m 3d6 frio; apaga chamas (1/combate)."),
("Passos de Geada", "Corre sobre agua congelada (24h)."),
("Toque Congelante", "Corpo a corpo reduz velocidade do alvo a metade (24h)."),
("Aura de Congelamento", "Agua a 3m congela; alvos molhados Restringidos (24h)."),
("Gelo Espinhoso", "Ao sofrer dano fisico, atacante toma 1d6 frio (24h)."),
("Absorção de Frio", "Primeiro ataque de frio recebido cura 2d6 HP (1/combate)."),
]),
("042", "YETI", [
("Sangue Anticongelante", "Imunidade total a frio (24h)."),
("Olhar Paralisante", "Contato visual CD 13 CON ou Paralisado de medo 1 turno (1/alvo/combate)."),
("Abraço Esmagador", "Agarramento automatico; +1d8 frio/turno (24h)."),
("Pelagem de Tundra", "Ganha 5 HP temporarios a cada hora (24h)."),
("Visao no Escuro Aprimorada", "Visao perfeita 36m no escuro (24h)."),
("Toque Congelante", "Corpo a corpo reduz velocidade a metade (24h)."),
("Gordura Calorica", "+20 HP temporarios ao comer; resistência a clima frio (24h)."),
("Gelo Espinhoso", "1d6 frio a quem acertar você corpo a corpo (24h)."),
]),
("043", "LOBO DO INVERNO", [
("Sopro de Frio", "Cone 4,5m 4d8 frio CD 13 CON ou Paralisado 1 turno (1/combate)."),
("Tática de Matilha", "Vantagem se aliado adjacente ao alvo (24h)."),
("Rastreio por Calor", "Detecta criaturas quentes a 30m no escuro (24h)."),
("Sangue Anticongelante", "Imune a frio (24h)."),
("Velocidade de Matilha", "+6m movimento (24h)."),
("Mordida Glacial", "Mordidas +1d6 frio (24h)."),
("Uivo Desorientador", "CD 12 CON ou Desvantagem em Percepção 1 min (1/combate)."),
("Pelagem de Tundra", "5 HP temporarios por hora (24h)."),
]),
("044", "MIMICO DE BAUL", [
("Camuflagem Perfeita", "Imovel, indistinguivel de objeto comum (24h)."),
("Lingua Adesiva", "Lingua 3m desarma ou puxa objeto (24h)."),
("Superficie Adesiva", "Quem tocar você Agarrado CD 13 FOR (24h)."),
("Saliva Acida", "Alvo agarrado 1d6 ácido/turno (24h)."),
("Pele Mutavel", "Altera cor e textura superficial (24h)."),
("Mordida Surpresa", "Mordida em alvo que não notou voce: triplo dano (1/combate)."),
("Bolsa Dimensional Gastrica", "Engole itens pequenos sem ganhar peso, max 10 kg (24h)."),
("Metabolismo de Material", "Resistência fisica baseada no ultimo material imitado (24h)."),
]),
("045", "METAMORFO DÚBIO", [
("Pele Mutavel", "Copia aparência e voz de humanoide observado 10 min (24h)."),
("Leitura Mental", "18m: le pensamentos superficiais do alvo focado (24h)."),
("Ataque Surpresa", "+3d6 se alvo não souber da mutação/identidade (24h)."),
("Juntas Articuladas", "Escapa de restricoes com Vantagem (24h)."),
("Camuflagem Perfeita", "Imovel, imita objeto humanoide pequeno (24h)."),
("Metabolismo de Material", "Resistência a tipo de dano do ultimo humanoide copiado (24h)."),
("Voz Copiada", "Vantagem em Enganação ao imitar voz (24h)."),
("Instinto Paranoico", "Vantagem em testes contra ilusao e charm (24h)."),
]),
("046", "HIDRA DAS CAVERNAS", [
("Regeneração de Cabecas", "Quando cai a 0 HP, se mutação ativa: revive com 25% HP uma vez por descansó longo (24h)."),
("Mordidas Multiplas", "Ação bônus: segundo ataque de mordida (24h)."),
("Veneno de Cabeca", "Uma mordida/turno CD 13 CON ou 2d6 veneno/turno por 3 turnos (24h)."),
("Mordida Acida", "Mordidas +2d6 ácido (24h)."),
("Saliva Adesiva", "Acerto CD 14 FOR ou Restringido (1/alvo/combate)."),
("Cabeca Hipnotica", "CD 14 SAB ou incapaz de atacar hidra 1 turno (1/combate)."),
("Couro Regenerativo", "Recupera 1d8 HP no inicio de cada turno (24h)."),
("Furia de Cabecas", "+1 ataque por turno enquanto abaixo de 50% HP (24h)."),
]),
("047", "QUIMERA", [
("Tres Ataques", "Ação bônus: terceiro ataque corpo a corpo (24h)."),
("Baforada Caotica", "Cone 6m: rola 1d3 fogo, relâmpago ou ácido 5d8 (1/combate)."),
("Multiplas Consciencias", "Imune a charm, medo e confusao (24h)."),
("Garras de Leao", "Corpo a corpo +2d6 (24h)."),
("Chifres de Cabra", "Investida 3m: +2d8 perfurante (24h)."),
("Mordida de Dragão", "Mordidas +2d6 fogo (24h)."),
("Voo Verdadeiro", "Voo 12m (24h)."),
("Fusao Magica", "Escolhe 2 habilidades de assimilação de outros monstros ja comidos na campanha por 12h (único efeito estendido)."),
]),
("048", "ANJO CAIDO", [
("Resistência Lendaria", "Duas vezes por combate, falha vira sucessó (24h)."),
("Aura Divina Corrompida", "Aliados a 10m +3 CA; inimigos na aura 1d6 sagrado/necrótico no inicio do turno (24h)."),
("Voo Perfeito", "Voo 18m; imune a quedas (24h)."),
("Magia Dual", "Prepara 1 magia divina e 1 sombria adicional nv. 3 ou menos (24h)."),
("Resistência Radiante e Necrotica", "Resistência a radiante e necrótico (24h)."),
("Espada Flamejante", "Ataques corpo a corpo +2d6 sagrado ou necrótico alternado (24h)."),
("Imunidade a Encantamento", "Imune a charm e veneno (24h)."),
("Pena Angelical", "Emite luz eterna 18m; uma vez por dia cura 4d8 removendo doenca ou maldicao (24h)."),
]),
("049", "GARGULA DE CRISTAL", [
("Falsa Aparencia", "Imovel, indistinguivel de cristal (24h)."),
("Mergulho de Pedra", "Cair 4,5m antes de atacar: +4d6 dano (24h)."),
("Forma de Pedra", "1/dia, imovel 1 minuto: invulneravel (24h)."),
("Camuflagem Perfeita", "Vantagem em Furtividade em ambiente rochosó (24h)."),
("Resistência a Cortante", "Resistência a cortante e perfurante (24h)."),
("Garras de Cristal", "Desarmado 1d8 cortante (24h)."),
("Voo de Planagem", "Voo 12m (24h)."),
("Reflexo Prismatico", "Uma vez por combate, redireciona feitico de luz (24h)."),
]),
("050", "ABERRACAO TENTACULAR", [
("Tentaculos Psiquicos", "Ataques a distancia 18m causam 2d6 psiquico; foco em até 3 alvos/turno (24h)."),
("Controle Mental", "Acerto CD 16 INT ou Dominado 1 minuto (1/alvo/combate)."),
("Ilusao Coletiva", "Raio 9m CD 17 SAB ou cenario falsó 10 min (1/dia)."),
("Leitura Mental", "18m: pensamentos superficiais (24h)."),
("Voz de Tumba", "Telepatia 30m; CD 12 SAB ou Amedrontado (1/combate)."),
("Absorção Psiquica", "Ao reduzir criatura a 0 HP, aprende 1 fato que ela sabia (24h)."),
("Resistência Psiquica", "Resistência a psiquico; imune a veneno (24h)."),
("Corpo Translucido", "Vantagem em Furtividade em penumbra (24h)."),
]),
("051", "BASILISCO DE MAGMA", [
("Olhar de Lava", "CD 13 CON ou Petrificado em rocha vulcanica quente 1d6 fogo/turno (1/alvo/combate)."),
("Sangue Fervente", "Imune a fogo; 50% resistência a magma (24h)."),
("Pele de Obsidiana", "Ignora dano extra de críticos (24h)."),
("Banhista de Magma", "Recupera 10 HP ao entrar em contato com fogo ou magma (1/turno, 24h)."),
("Imunidade a Petrificação", "Imune a petrificação comum (24h)."),
("Toque Cauterizante", "Corpo a corpo +2d6 fogo (24h)."),
("Escamas de Obsidiana", "+3 CA (24h)."),
("Mordida Ignea", "Mordidas +2d6 fogo (24h)."),
]),
("052", "SEREIA DAS PROFUNDEZAS", [
("Canto Encantador", "Ouvintes CD 14 SAB ou Encantados movem-se ao canto (1/combate)."),
("Anfibia Perfeita", "Sem penalidade em terra ou agua (24h)."),
("Guelras de Profundeza", "Respiração aquatica infinita (24h)."),
("Radar de Linha Lateral", "Sente movimento atras de paredes ou agua (24h)."),
("Camuflagem de Polvo", "Invisivel colado a rocha umida (24h)."),
("Arrasto de Mare", "Alvo Encantado adjacent e puxado 6m em direcao a agua (24h)."),
("Pele Escorregadia", "Impossivel ser agarrado (24h)."),
("Voz de Abismo", "Vantagem em Performance vocal; eco atravessa pedra 30m (24h)."),
]),
("053", "TROLL DE PEDRA", [
("Regeneração", "Recupera 10 HP no inicio de cada turno; fogo ou ácido suspende 1 turno (24h)."),
("Mordida Rasgadora", "Mordida acima de 15 dano: alvo Prostrado (24h)."),
("Estômago Universal", "Imune a venenos e doenças por ingestão (24h)."),
("Pele de Pedra", "+2 CA; resistência a contundente (24h)."),
("Garras de Rocha", "Dois ataques de garra 1d6+mod FOR (24h)."),
("Bilis de Troll", "Arma revestida +2d6 ácido por 3 turnos (1/combate)."),
("Fome de Pedra", "Pode mastigar pedra ou metal para recuperar 1d6 HP (1/dia)."),
("Resistência a Queda", "Sem dano de quedas até 6m (24h)."),
]),
("054", "CICLOPE", [
("Porrada Devastadora", "Linha 3m CD 16 DES ou metade de 3d10 contundente (1/combate)."),
("Alcance Imenso", "Ataca criaturas a 3m sem penalidade (24h)."),
("Olho Unico", "Vantagem em Percepção a longa distancia; Desvantagem em ataques a mais de 18m (24h)."),
("Força Colossal", "+4 Forca; empurrao em acerto 3m (24h)."),
("Pele Grossa", "+2 CA (24h)."),
("Investida de Gigante", "Mover 6m em linha reta: +2d10 no próximo acerto (24h)."),
("Resistência a Medo", "Imune a intimidação de criaturas menores (24h)."),
("Carne de Gigante", "+8 HP máximo permanentes (único por Ciclope na vida do personagem; mutação permanente)."),
]),
("055", "HARPIA DE CAVERNA", [
("Ataque em Mergulho", "Cair 6m antes de atacar: dano dobrado (24h)."),
("Grito Ensurdecedor", "CD 13 CON ou Ensurdecido 1 min (1/combate)."),
("Asas de Planagem", "Planar e queda segura 15m (24h)."),
("Vocalizacao Sonica", "Grito CD 13 CON ou Atordoado 1 turno (1/combate)."),
("Plumagem Furtiva", "Vantagem em Furtividade (24h)."),
("Garras de Rapina", "Ataques corpo a corpo +1d6 (24h)."),
("Visao de Rapina", "Sem penalidade tiros longa distancia (24h)."),
("Ossos Ocos", "Sem dano quedas 15m (24h)."),
]),
("056", "ROPER", [
("Camuflagem Total", "Imovel, indistinguivel de estalactite (24h)."),
("Tentaculos de Alcance", "Ataques corpo a corpo alcance 9m (24h)."),
("Quatro Tentaculos", "Pode agarrar até 2 alvos; puxa 3m em acerto (24h)."),
("Drenagem de Forca", "Alvo agarrado perde 2 FOR temporarios/turno, recupera em descansó longo (24h)."),
("Olho de Abismo", "Visao no escuro 60m (24h)."),
("Resistência a Queda", "Agarrado a teto: imune a queda involuntaria (24h)."),
("Armadura de Pedra", "+4 CA quando imovel (24h)."),
("Mordida de Roper", "Mordida contra agarrado +2d8 (24h)."),
]),
("057", "ABOLETH", [
("Escravizacao", "CD 19 SAB ou obedece ordem telepatica do aboleth até descansó longo (1/alvo/combate)."),
("Memoria Ancestral", "Uma pergunta por dia sobre historia ou segredo conhecido por qualquer morto consumido (24h)."),
("Muco Transformador", "Contato prolongado: pele exige imersao em agua 1h/dia ou 1d6 necrótico (24h; efeito simbólico)."),
("Tentaculos Abissais", "Tres ataques tentaculo alcance 3m +2d6 (24h)."),
("Telepatia Profunda", "Comunica-se telepaticamente 36m; le emocoes (24h)."),
("Resistência Lendaria", "Uma vez por combate, falha vira sucessó (24h)."),
("Visao no Escuro Aquatica", "Visao 36m agua ou umida (24h)."),
("Domínio Psiquico", "Imune a charm; Vantagem contra ilusao (24h)."),
]),
("058", "PUDIM NEGRO", [
("Corrosao de Metal", "Contato 3 turnos dissolve armadura metalica -2 CA cumulativo (24h)."),
("Divisao Amorfa", "Primeiro ataque cortante por combaté causa metade do dano (24h)."),
("Amorfismo", "Passa por frestas de 1 cm (24h)."),
("Corpo de Lodo", "Imune a crítico perfurante; resistência ácido (24h)."),
("Toque Dissolvente", "Corpo a corpo +3d8 ácido (24h)."),
("Imunidade a Ácido", "Imune a ácido (24h)."),
("Englobamento", "CD 14 FOR ou Restringido e 2d8 ácido/turno (1/alvo/combate)."),
("Nucleo Negro", "Uma vez por dia, ignora efeito que reduziria a 0 HP e fica com 1 HP (24h)."),
]),
("059", "LAGOSTA-GIGANTE ABISSAL", [
("Pinça Esmagadora", "Agarramento automatico CD 14 FOR; 2d8/turno (24h)."),
("Exoesqueleto Reforçado", "Ignora primeiros 5 de dano por ataque (24h)."),
("Guelras de Profundeza", "Respiração aquatica infinita (24h)."),
("Radar de Linha Lateral", "Detecta movimento atras de paredes finas ou agua (24h)."),
("Armadura Fina", "+2 CA (24h)."),
("Resistência Abissal", "Imune a pressao e esmagamento (24h)."),
("Antena Sensorial", "Vantagem em Percepção subaquatica (24h)."),
("Garra Cortante", "Desarmado 1d8 cortante; +2 em testes para quebrar casca (24h)."),
]),
("060", "CARANGUEJO-EREMITA COLOSSAL", [
("Concha Improvisada", "+5 CA enquanto mutação ativa; reduz dano de projeteis pela metade (24h)."),
("Investida Lateral", "Mover 6m e atacar: empurra alvos 3m (24h)."),
("Resistência Abissal", "Imune a pressao extrema (24h)."),
("Pele Escorregadia", "Impossivel ser agarrado (24h)."),
("Guelras de Profundeza", "Respiração aquatica infinita (24h)."),
("Garra Colossal", "Ataques corpo a corpo +2d6; empurrao 3m (24h)."),
("Casco de Navio", "Resistência a contundente e perfurante no-magico (24h)."),
("Camuflagem de Casco", "Vantagem em Furtividade imitando objeto grande (24h)."),
]),
]

out = Path(__file__).resolve().parents[1] / "livros" / "ASSIMILACAO-POR-ESPECIME.md"
lines = [intro]
for cod, title, abilities in monsters:
    assert len(abilities) == 8, f"{cod} has {len(abilities)} abilities"
    lines.append(f"## {cod} — {title}\n\n")
    lines.append("| # | Habilidade | Efeito |\n")
    lines.append("|---|-----------|--------|\n")
    for i, (name, effect) in enumerate(abilities, 1):
        lines.append(f"| {i} | {name} | {effect} |\n")
    lines.append("\n")

lines.append("---\n\n")
lines.append("## INDICE — ASSIMILACAO POR ESPECIME\n\n")
lines.append("| Cod | Monstro | Seção |\n")
lines.append("|-----|---------|-------|\n")
for cod, title, _ in monsters:
    lines.append(f"| {cod} | {title} | ## {cod} |\n")

text = "".join(lines)
out.write_text(text, encoding="utf-8")

sections = len(re.findall(r"^## \d{3}", text, re.M))
rows = len(re.findall(r"^\| [1-8] \|", text, re.M))
print(f"written: {out}")
print(f"sections={sections} rows={rows} bytes={out.stat().st_size}")
