import type { BattleScene } from "./types";
import { defaultMovementFields } from "./movement";

export const DEMO_SCENE: BattleScene = {
  id: "demo",
  name: "Masmorra — Sala Hex",
  gridRadius: 8,
  hexSize: 36,
  tokens: [
    {
      id: "t1",
      name: "Aventureiro",
      axial: { q: 0, r: 0 },
      color: "#4a90d9",
      walk: 4,
      run: 7,
      pa: 0,
      paMax: 5,
      ownerRole: "jogador",
      actorId: "pc-aventureiro",
      linked: true,
      nivel: 3,
      vida: 28,
      vidaMax: 28,
      defesa: 13,
      ...defaultMovementFields({ walk: 4, run: 7 }),
    },
    {
      id: "t5",
      name: "Lyra Cantochama",
      axial: { q: -1, r: 1 },
      color: "#d4a84b",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 5,
      ownerRole: "jogador",
      actorId: "pc-bardo-suporte",
      linked: true,
      nivel: 3,
      vida: 22,
      vidaMax: 22,
      defesa: 12,
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
    {
      id: "t3",
      name: "Aventureira Maga",
      axial: { q: -2, r: 0 },
      color: "#9b59b6",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 5,
      ownerRole: "jogador",
      actorId: "pc-aventureira-maga",
      linked: true,
      nivel: 5,
      vida: 32,
      vidaMax: 32,
      defesa: 12,
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
    {
      id: "t2",
      name: "Goblin",
      axial: { q: 1, r: 0 },
      color: "#8b4513",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 6,
      ownerRole: "mestre",
      nivel: 1,
      vida: 7,
      vidaMax: 7,
      defesa: 13,
      monsterEntryId: "monstros-goblin",
      monsterTier: "mob",
      creatureSize: "small",
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
    {
      id: "t4",
      name: "Goblin",
      axial: { q: 3, r: 0 },
      color: "#8b4513",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 6,
      ownerRole: "mestre",
      nivel: 1,
      vida: 7,
      vidaMax: 7,
      defesa: 13,
      monsterEntryId: "monstros-goblin",
      monsterTier: "mob",
      creatureSize: "small",
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
    {
      id: "t5",
      name: "Goblin",
      axial: { q: 2, r: -1 },
      color: "#8b4513",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 6,
      ownerRole: "mestre",
      nivel: 1,
      vida: 7,
      vidaMax: 7,
      defesa: 13,
      monsterEntryId: "monstros-goblin",
      monsterTier: "mob",
      creatureSize: "small",
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
    {
      id: "t6",
      name: "Esqueleto",
      axial: { q: 1, r: 2 },
      color: "#c9a962",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 6,
      ownerRole: "mestre",
      nivel: 2,
      vida: 18,
      vidaMax: 18,
      defesa: 13,
      monsterEntryId: "monstros-esqueleto-armado",
      monsterTier: "mob",
      creatureSize: "medium",
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
    {
      id: "t7",
      name: "Minotauro",
      axial: { q: -4, r: 2 },
      color: "#6b5344",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 6,
      ownerRole: "mestre",
      nivel: 6,
      vida: 52,
      vidaMax: 52,
      defesa: 14,
      monsterEntryId: "monstros-minotauro",
      monsterTier: "mini",
      creatureSize: "large",
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
    {
      id: "t8",
      name: "Escorpião Gigante",
      axial: { q: 5, r: -2 },
      color: "#7a4a6a",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 6,
      ownerRole: "mestre",
      nivel: 3,
      vida: 52,
      vidaMax: 52,
      defesa: 15,
      monsterEntryId: "monstros-escorpiao-gigante",
      monsterTier: "mob",
      creatureSize: "huge",
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
  ],
};
