import type { BattleScene } from "./types";
import { defaultMovementFields } from "./movement";

export const DEMO_SCENE: BattleScene = {
  id: "demo",
  name: "Masmorra — Sala de Combate",
  gridRadius: 8,
  cellSize: 36,
  tokens: [
    {
      id: "t1",
      name: "Thrain Ferroescudo",
      axial: { q: 0, r: 0 },
      color: "#6b8cae",
      walk: 4,
      run: 7,
      pa: 0,
      paMax: 5,
      ownerRole: "jogador",
      actorId: "pc-thrain-ferroescudo",
      linked: true,
      nivel: 6,
      vida: 64,
      vidaMax: 64,
      defesa: 15,
      ...defaultMovementFields({ walk: 4, run: 7 }),
    },
    {
      id: "t3",
      name: "Lyanna Umbral",
      axial: { q: -2, r: 0 },
      color: "#9b59b6",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 5,
      ownerRole: "jogador",
      actorId: "pc-lyanna-umbral",
      linked: true,
      nivel: 6,
      vida: 38,
      vidaMax: 38,
      defesa: 13,
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
    {
      id: "t5",
      name: "Maelis Purificador",
      axial: { q: -1, r: 1 },
      color: "#d4c44b",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 5,
      ownerRole: "jogador",
      actorId: "pc-maelis-purificador",
      linked: true,
      nivel: 6,
      vida: 45,
      vidaMax: 45,
      defesa: 14,
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
    {
      id: "t10",
      name: "Pippin Sussurro",
      axial: { q: 1, r: -1 },
      color: "#5c9e6a",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 5,
      ownerRole: "jogador",
      actorId: "pc-pippin-sussurro",
      linked: true,
      nivel: 6,
      vida: 39,
      vidaMax: 39,
      defesa: 15,
      creatureSize: "small",
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
    {
      id: "t2",
      name: "Goblin 1",
      axial: { q: 1, r: 0 },
      color: "#8b4513",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 6,
      ownerRole: "mestre",
      nivel: 1,
      vida: 7,
      vidaMax: 7,
      defesa: 13,
      monsterEntryId: "monstros-goblin",
      monsterTier: "mob",
      creatureSize: "small",
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
    {
      id: "t4",
      name: "Goblin 2",
      axial: { q: 3, r: 0 },
      color: "#8b4513",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 6,
      ownerRole: "mestre",
      nivel: 1,
      vida: 7,
      vidaMax: 7,
      defesa: 13,
      monsterEntryId: "monstros-goblin",
      monsterTier: "mob",
      creatureSize: "small",
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
    {
      id: "t9",
      name: "Goblin 3",
      axial: { q: 2, r: -1 },
      color: "#8b4513",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 6,
      ownerRole: "mestre",
      nivel: 1,
      vida: 7,
      vidaMax: 7,
      defesa: 13,
      monsterEntryId: "monstros-goblin",
      monsterTier: "mob",
      creatureSize: "small",
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
    {
      id: "t6",
      name: "Esqueleto",
      axial: { q: 1, r: 2 },
      color: "#c9a962",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 6,
      ownerRole: "mestre",
      nivel: 2,
      vida: 18,
      vidaMax: 18,
      defesa: 13,
      monsterEntryId: "monstros-esqueleto-armado",
      monsterTier: "mob",
      creatureSize: "medium",
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
    {
      id: "t7",
      name: "Minotauro",
      axial: { q: -4, r: 2 },
      color: "#6b5344",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 6,
      ownerRole: "mestre",
      nivel: 6,
      vida: 52,
      vidaMax: 52,
      defesa: 14,
      monsterEntryId: "monstros-minotauro",
      monsterTier: "mini",
      creatureSize: "large",
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
    {
      id: "t8",
      name: "Escorpião Gigante",
      axial: { q: 5, r: -2 },
      color: "#7a4a6a",
      walk: 4,
      run: 6,
      pa: 0,
      paMax: 6,
      ownerRole: "mestre",
      nivel: 3,
      vida: 52,
      vidaMax: 52,
      defesa: 15,
      monsterEntryId: "monstros-escorpiao-gigante",
      monsterTier: "mob",
      creatureSize: "huge",
      ...defaultMovementFields({ walk: 4, run: 6 }),
    },
  ],
};
