/** Só Google/Discord — esconde e-mail, senha e divisores do formulário Clerk. */
export const clerkSocialOnlyAppearance = {
  layout: {
    socialButtonsPlacement: "top",
    socialButtonsVariant: "blockButton",
    showOptionalFields: false,
  },
  elements: {
    rootBox: { width: "100%" },
    card: {
      background: "transparent",
      boxShadow: "none",
      border: "none",
      gap: "0.65rem",
    },
    headerTitle: { display: "none" },
    headerSubtitle: { display: "none" },
    socialButtonsBlockButton: {
      fontSize: "0.9rem",
      fontWeight: "600",
    },
    dividerRow: { display: "none" },
    dividerText: { display: "none" },
    formFieldRow: { display: "none" },
    formFieldRow__emailAddress: { display: "none" },
    formFieldRow__password: { display: "none" },
    formFieldRow__identifier: { display: "none" },
    formFieldInput: { display: "none" },
    formFieldLabel: { display: "none" },
    formButtonPrimary: { display: "none" },
    formFieldAction: { display: "none" },
    footerAction: { display: "none" },
    footerActionLink: { display: "none" },
    footer: { display: "none" },
    identityPreview: { display: "none" },
    identityPreviewEditButton: { display: "none" },
    alternativeMethodsBlockButton: { display: "none" },
    backRow: { display: "none" },
    backLink: { display: "none" },
    otpCodeFieldInput: { display: "none" },
    formResendCodeLink: { display: "none" },
  },
};
